// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Content for Category documents
 */
interface CategoryDocumentData {
  /**
   * Name field in *Category*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Category name (e.g., Basketball, Soccer)
   * - **API ID Path**: category.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Icon field in *Category*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: category.icon
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<"thumbnail"> /**
   * Meta Title field in *Category*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the category used for social media and search engines
   * - **API ID Path**: category.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Category*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the category
   * - **API ID Path**: category.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Category*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: category.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Category document from Prismic
 *
 * - **API ID**: `category`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CategoryDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<CategoryDocumentData>,
    "category",
    Lang
  >;

/**
 * Item in *Event → Sponsors*
 */
export interface EventDocumentDataSponsorsItem {
  /**
   * Sponsor field in *Event → Sponsors*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: event.sponsors[].sponsor
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  sponsor: prismic.ContentRelationshipField<"sponsor">;
}

/**
 * Content for Event documents
 */
interface EventDocumentData {
  /**
   * Title field in *Event*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Event name (e.g., NBA Finals: Lakers vs Celtics)
   * - **API ID Path**: event.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Category field in *Event*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: Select event category
   * - **API ID Path**: event.category
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  category: prismic.ContentRelationshipField<"category">;

  /**
   * Event Date & Time field in *Event*
   *
   * - **Field Type**: Timestamp
   * - **Placeholder**: Select event date and time
   * - **API ID Path**: event.date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#timestamp
   */
  date: prismic.TimestampField;

  /**
   * Cover Image field in *Event*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: event.cover_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  cover_image: prismic.ImageField<"thumbnail">;

  /**
   * Description field in *Event*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Long-form description of the event
   * - **API ID Path**: event.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Location field in *Event*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Venue name or address
   * - **API ID Path**: event.location
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  location: prismic.KeyTextField;

  /**
   * Sponsors field in *Event*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: event.sponsors[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  sponsors: prismic.GroupField<Simplify<EventDocumentDataSponsorsItem>>;

  /**
   * Tags field in *Event*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Comma-separated tags for filtering and SEO
   * - **API ID Path**: event.tags
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tags: prismic.KeyTextField /**
   * Meta Title field in *Event*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the event used for social media and search engines
   * - **API ID Path**: event.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Event*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the event
   * - **API ID Path**: event.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Event*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: event.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Event document from Prismic
 *
 * - **API ID**: `event`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type EventDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<EventDocumentData>, "event", Lang>;

/**
 * Item in *Footer → About Us Links*
 */
export interface FooterDocumentDataAboutUsLinksItem {
  /**
   * Link Text field in *Footer → About Us Links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Link display text
   * - **API ID Path**: footer.aboutUsLinks[].linkText
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  linkText: prismic.KeyTextField;

  /**
   * Link URL field in *Footer → About Us Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Link destination
   * - **API ID Path**: footer.aboutUsLinks[].linkUrl
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  linkUrl: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Item in *Footer → Get In Touch Links*
 */
export interface FooterDocumentDataGetInTouchLinksItem {
  /**
   * Link Text field in *Footer → Get In Touch Links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Link display text
   * - **API ID Path**: footer.getInTouchLinks[].linkText
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  linkText: prismic.KeyTextField;

  /**
   * Link URL field in *Footer → Get In Touch Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Link destination
   * - **API ID Path**: footer.getInTouchLinks[].linkUrl
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  linkUrl: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Item in *Footer → Social Links*
 */
export interface FooterDocumentDataSocialLinksItem {
  /**
   * Platform field in *Footer → Social Links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g., Facebook, Twitter, Instagram
   * - **API ID Path**: footer.socialLinks[].platform
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  platform: prismic.KeyTextField;

  /**
   * Link URL field in *Footer → Social Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Social media link
   * - **API ID Path**: footer.socialLinks[].linkUrl
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  linkUrl: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Content for Footer documents
 */
interface FooterDocumentData {
  /**
   * Description field in *Footer*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Company description text
   * - **API ID Path**: footer.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Address field in *Footer*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Company address
   * - **API ID Path**: footer.address
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  address: prismic.RichTextField;

  /**
   * About Us Links field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.aboutUsLinks[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  aboutUsLinks: prismic.GroupField<
    Simplify<FooterDocumentDataAboutUsLinksItem>
  >;

  /**
   * Get In Touch Links field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.getInTouchLinks[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  getInTouchLinks: prismic.GroupField<
    Simplify<FooterDocumentDataGetInTouchLinksItem>
  >;

  /**
   * Social Links field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.socialLinks[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  socialLinks: prismic.GroupField<Simplify<FooterDocumentDataSocialLinksItem>>;
}

/**
 * Footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<FooterDocumentData>,
    "footer",
    Lang
  >;

/**
 * Item in *Navigation → Links*
 */
export interface NavigationDocumentDataLinksItem {
  /**
   * Label field in *Navigation → Links*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Optional - Label for the link
   * - **API ID Path**: navigation.links[].label
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  label: prismic.TitleField;

  /**
   * Link field in *Navigation → Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Link for navigation item
   * - **API ID Path**: navigation.links[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Content for Navigation documents
 */
interface NavigationDocumentData {
  /**
   * Links field in *Navigation*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.links[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  links: prismic.GroupField<Simplify<NavigationDocumentDataLinksItem>>;
}

/**
 * Navigation document from Prismic
 *
 * - **API ID**: `navigation`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavigationDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<NavigationDocumentData>,
    "navigation",
    Lang
  >;

type PageDocumentDataSlicesSlice =
  | StudioAccordionSlice
  | SponsorSliderSlice
  | ServicesGridSlice
  | AboutSectionSlice
  | EventListingSlice
  | GsapSliderSlice
  | HeroSlice
  | QuoteSlice
  | TextSlice
  | ImageSlice
  | ImageCardsSlice
  | TextWithImageSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Parent field in *Page*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: page.parent
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  parent: prismic.ContentRelationshipField<"page">;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
  /**
   * Site Title field in *Settings*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Title of the site
   * - **API ID Path**: settings.siteTitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  siteTitle: prismic.TitleField;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    "settings",
    Lang
  >;

/**
 * Content for Sponsor documents
 */
interface SponsorDocumentData {
  /**
   * Title field in *Sponsor*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Name of sponsor
   * - **API ID Path**: sponsor.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Logo field in *Sponsor*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: sponsor.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<"thumbnail">;

  /**
   * Description field in *Sponsor*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Information about the sponsor
   * - **API ID Path**: sponsor.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Website URL field in *Sponsor*
   *
   * - **Field Type**: Link
   * - **Placeholder**: External link to sponsor's website
   * - **API ID Path**: sponsor.website_url
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  website_url: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  > /**
   * Meta Title field in *Sponsor*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the sponsor used for social media and search engines
   * - **API ID Path**: sponsor.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Sponsor*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the sponsor
   * - **API ID Path**: sponsor.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Sponsor*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: sponsor.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Sponsor document from Prismic
 *
 * - **API ID**: `sponsor`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SponsorDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SponsorDocumentData>,
    "sponsor",
    Lang
  >;

export type AllDocumentTypes =
  | CategoryDocument
  | EventDocument
  | FooterDocument
  | NavigationDocument
  | PageDocument
  | SettingsDocument
  | SponsorDocument;

/**
 * Item in *AboutSection → Default → Primary → Features*
 */
export interface AboutSectionSliceDefaultPrimaryFeaturesItem {
  /**
   * Feature Icon field in *AboutSection → Default → Primary → Features*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about_section.default.primary.features[].featureIcon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  featureIcon: prismic.ImageField<never>;

  /**
   * Feature Title field in *AboutSection → Default → Primary → Features*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter feature title
   * - **API ID Path**: about_section.default.primary.features[].featureTitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  featureTitle: prismic.KeyTextField;

  /**
   * Feature Description field in *AboutSection → Default → Primary → Features*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter feature description
   * - **API ID Path**: about_section.default.primary.features[].featureDescription
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  featureDescription: prismic.RichTextField;
}

/**
 * Primary content in *AboutSection → Default → Primary*
 */
export interface AboutSectionSliceDefaultPrimary {
  /**
   * Title field in *AboutSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter main title
   * - **API ID Path**: about_section.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Subtitle field in *AboutSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter subtitle
   * - **API ID Path**: about_section.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField;

  /**
   * Description field in *AboutSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter description
   * - **API ID Path**: about_section.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Features field in *AboutSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: about_section.default.primary.features[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  features: prismic.GroupField<
    Simplify<AboutSectionSliceDefaultPrimaryFeaturesItem>
  >;
}

/**
 * Default variation for AboutSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: About Section
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AboutSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *AboutSection*
 */
type AboutSectionSliceVariation = AboutSectionSliceDefault;

/**
 * AboutSection Shared Slice
 *
 * - **API ID**: `about_section`
 * - **Description**: About Section with title, subtitle, description and repeatable feature boxes
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutSectionSlice = prismic.SharedSlice<
  "about_section",
  AboutSectionSliceVariation
>;

/**
 * Primary content in *EventListing → Default → Primary*
 */
export interface EventListingSliceDefaultPrimary {
  /**
   * Title field in *EventListing → Default → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Events title...
   * - **API ID Path**: event_listing.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;
}

/**
 * Default variation for EventListing Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type EventListingSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<EventListingSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *EventListing*
 */
type EventListingSliceVariation = EventListingSliceDefault;

/**
 * EventListing Shared Slice
 *
 * - **API ID**: `event_listing`
 * - **Description**: Event Listing
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type EventListingSlice = prismic.SharedSlice<
  "event_listing",
  EventListingSliceVariation
>;

/**
 * Primary content in *GsapSlider → Items*
 */
export interface GsapSliderSliceDefaultItem {
  /**
   * Title field in *GsapSlider → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter slide title
   * - **API ID Path**: gsap_slider.items[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *GsapSlider → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter slide description
   * - **API ID Path**: gsap_slider.items[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * CTA Text field in *GsapSlider → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Learn More
   * - **API ID Path**: gsap_slider.items[].ctaText
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  ctaText: prismic.KeyTextField;

  /**
   * CTA Link field in *GsapSlider → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: gsap_slider.items[].ctaLink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  ctaLink: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Background Image field in *GsapSlider → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: gsap_slider.items[].backgroundImage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  backgroundImage: prismic.ImageField<never>;
}

/**
 * Default variation for GsapSlider Slice
 *
 * - **API ID**: `default`
 * - **Description**: GsapSlider
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type GsapSliderSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<GsapSliderSliceDefaultItem>
>;

/**
 * Slice variation for *GsapSlider*
 */
type GsapSliderSliceVariation = GsapSliderSliceDefault;

/**
 * GsapSlider Shared Slice
 *
 * - **API ID**: `gsap_slider`
 * - **Description**: GsapSlider
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type GsapSliderSlice = prismic.SharedSlice<
  "gsap_slider",
  GsapSliderSliceVariation
>;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Text field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * Button Link field in *Hero → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.buttonLink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  buttonLink: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Button Text field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.buttonText
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  buttonText: prismic.KeyTextField;

  /**
   * Background Image field in *Hero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.backgroundImage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  backgroundImage: prismic.ImageField<never>;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Primary content in *Image → Default → Primary*
 */
export interface ImageSliceDefaultPrimary {
  /**
   * Image field in *Image → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for Image Slice
 *
 * - **API ID**: `default`
 * - **Description**: Image
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ImageSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Image → Banner → Primary*
 */
export interface ImageSliceBannerPrimary {
  /**
   * Image field in *Image → Banner → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image.banner.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Banner variation for Image Slice
 *
 * - **API ID**: `banner`
 * - **Description**: Image
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageSliceBanner = prismic.SharedSliceVariation<
  "banner",
  Simplify<ImageSliceBannerPrimary>,
  never
>;

/**
 * Slice variation for *Image*
 */
type ImageSliceVariation = ImageSliceDefault | ImageSliceBanner;

/**
 * Image Shared Slice
 *
 * - **API ID**: `image`
 * - **Description**: Image
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageSlice = prismic.SharedSlice<"image", ImageSliceVariation>;

/**
 * Item in *ImageCards → Default → Primary → Cards*
 */
export interface ImageCardsSliceDefaultPrimaryCardsItem {
  /**
   * Image field in *ImageCards → Default → Primary → Cards*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_cards.default.primary.cards[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Text field in *ImageCards → Default → Primary → Cards*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_cards.default.primary.cards[].text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * Button Link field in *ImageCards → Default → Primary → Cards*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: image_cards.default.primary.cards[].buttonLink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  buttonLink: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Button Text field in *ImageCards → Default → Primary → Cards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_cards.default.primary.cards[].buttonText
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  buttonText: prismic.KeyTextField;
}

/**
 * Primary content in *ImageCards → Default → Primary*
 */
export interface ImageCardsSliceDefaultPrimary {
  /**
   * Heading field in *ImageCards → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_cards.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Cards field in *ImageCards → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: image_cards.default.primary.cards[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  cards: prismic.GroupField<Simplify<ImageCardsSliceDefaultPrimaryCardsItem>>;
}

/**
 * Default variation for ImageCards Slice
 *
 * - **API ID**: `default`
 * - **Description**: ImageCards
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageCardsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ImageCardsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ImageCards*
 */
type ImageCardsSliceVariation = ImageCardsSliceDefault;

/**
 * ImageCards Shared Slice
 *
 * - **API ID**: `image_cards`
 * - **Description**: ImageCards
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageCardsSlice = prismic.SharedSlice<
  "image_cards",
  ImageCardsSliceVariation
>;

/**
 * Primary content in *Quote → Default → Primary*
 */
export interface QuoteSliceDefaultPrimary {
  /**
   * Quote field in *Quote → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: quote.default.primary.quote
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  quote: prismic.RichTextField;

  /**
   * Source field in *Quote → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: quote.default.primary.source
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  source: prismic.KeyTextField;
}

/**
 * Default variation for Quote Slice
 *
 * - **API ID**: `default`
 * - **Description**: Quote
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type QuoteSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<QuoteSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Quote*
 */
type QuoteSliceVariation = QuoteSliceDefault;

/**
 * Quote Shared Slice
 *
 * - **API ID**: `quote`
 * - **Description**: Quote
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type QuoteSlice = prismic.SharedSlice<"quote", QuoteSliceVariation>;

/**
 * Primary content in *ServicesGrid → Default → Primary*
 */
export interface ServicesGridSliceDefaultPrimary {
  /**
   * Title field in *ServicesGrid → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: What We Do Best
   * - **API ID Path**: services_grid.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *ServicesGrid → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: From strategy to execution, our services are built to elevate your brand, engage your audience, and drive measurable growth.
   * - **API ID Path**: services_grid.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;
}

/**
 * Primary content in *ServicesGrid → Items*
 */
export interface ServicesGridSliceDefaultItem {
  /**
   * Card Size field in *ServicesGrid → Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Choose card size
   * - **Default Value**: square
   * - **API ID Path**: services_grid.items[].card_size
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  card_size: prismic.SelectField<
    "vertical" | "horizontal" | "square",
    "filled"
  >;

  /**
   * Service Description field in *ServicesGrid → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Brief description of the service
   * - **API ID Path**: services_grid.items[].service_description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  service_description: prismic.KeyTextField;

  /**
   * Background Image field in *ServicesGrid → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: services_grid.items[].background_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background_image: prismic.ImageField<never>;

  /**
   * Category field in *ServicesGrid → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: services_grid.items[].category
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  category: prismic.ContentRelationshipField<"category">;
}

/**
 * Default variation for ServicesGrid Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default variation
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServicesGridSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ServicesGridSliceDefaultPrimary>,
  Simplify<ServicesGridSliceDefaultItem>
>;

/**
 * Slice variation for *ServicesGrid*
 */
type ServicesGridSliceVariation = ServicesGridSliceDefault;

/**
 * ServicesGrid Shared Slice
 *
 * - **API ID**: `services_grid`
 * - **Description**: A grid layout displaying services with title, description, and background images
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServicesGridSlice = prismic.SharedSlice<
  "services_grid",
  ServicesGridSliceVariation
>;

/**
 * Primary content in *SponsorSlider → Default → Primary*
 */
export interface SponsorSliderSliceDefaultPrimary {
  /**
   * Title field in *SponsorSlider → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter the slider title
   * - **API ID Path**: sponsor_slider.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Description field in *SponsorSlider → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter a description for the sponsor slider
   * - **API ID Path**: sponsor_slider.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Button Text field in *SponsorSlider → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: View All Sponsors
   * - **API ID Path**: sponsor_slider.default.primary.buttonText
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  buttonText: prismic.KeyTextField;

  /**
   * Button Link field in *SponsorSlider → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Link to sponsors page or external URL
   * - **API ID Path**: sponsor_slider.default.primary.buttonLink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  buttonLink: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Primary content in *SponsorSlider → Items*
 */
export interface SponsorSliderSliceDefaultItem {
  /**
   * Sponsor field in *SponsorSlider → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: Select a sponsor
   * - **API ID Path**: sponsor_slider.items[].sponsor
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  sponsor: prismic.ContentRelationshipField<"sponsor">;
}

/**
 * Default variation for SponsorSlider Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default sponsor slider with title, description, and sponsor items
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SponsorSliderSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SponsorSliderSliceDefaultPrimary>,
  Simplify<SponsorSliderSliceDefaultItem>
>;

/**
 * Slice variation for *SponsorSlider*
 */
type SponsorSliderSliceVariation = SponsorSliderSliceDefault;

/**
 * SponsorSlider Shared Slice
 *
 * - **API ID**: `sponsor_slider`
 * - **Description**: A slider component showcasing sponsors with navigation controls
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SponsorSliderSlice = prismic.SharedSlice<
  "sponsor_slider",
  SponsorSliderSliceVariation
>;

/**
 * Primary content in *StudioAccordion → Default → Primary*
 */
export interface StudioAccordionSliceDefaultPrimary {
  /**
   * Section Title field in *StudioAccordion → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: The Studio
   * - **API ID Path**: studio_accordion.default.primary.sectionTitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  sectionTitle: prismic.KeyTextField;

  /**
   * Section Subtitle field in *StudioAccordion → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Architecture
   * - **API ID Path**: studio_accordion.default.primary.sectionSubtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  sectionSubtitle: prismic.KeyTextField;
}

/**
 * Primary content in *StudioAccordion → Items*
 */
export interface StudioAccordionSliceDefaultItem {
  /**
   * Panel Title field in *StudioAccordion → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Brief
   * - **API ID Path**: studio_accordion.items[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Panel Description field in *StudioAccordion → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Collect customer specifications and analyze demand to provide the best solutions
   * - **API ID Path**: studio_accordion.items[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Background Image field in *StudioAccordion → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: studio_accordion.items[].backgroundImage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  backgroundImage: prismic.ImageField<never>;
}

/**
 * Default variation for StudioAccordion Slice
 *
 * - **API ID**: `default`
 * - **Description**: StudioAccordion
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type StudioAccordionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<StudioAccordionSliceDefaultPrimary>,
  Simplify<StudioAccordionSliceDefaultItem>
>;

/**
 * Slice variation for *StudioAccordion*
 */
type StudioAccordionSliceVariation = StudioAccordionSliceDefault;

/**
 * StudioAccordion Shared Slice
 *
 * - **API ID**: `studio_accordion`
 * - **Description**: StudioAccordion
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type StudioAccordionSlice = prismic.SharedSlice<
  "studio_accordion",
  StudioAccordionSliceVariation
>;

/**
 * Primary content in *Text → Default → Primary*
 */
export interface TextSliceDefaultPrimary {
  /**
   * Text field in *Text → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text.default.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;
}

/**
 * Default variation for Text Slice
 *
 * - **API ID**: `default`
 * - **Description**: Text
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TextSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Text → Two Columns → Primary*
 */
export interface TextSliceTwoColumnsPrimary {
  /**
   * Text field in *Text → Two Columns → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text.twoColumns.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;
}

/**
 * Two Columns variation for Text Slice
 *
 * - **API ID**: `twoColumns`
 * - **Description**: Text
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextSliceTwoColumns = prismic.SharedSliceVariation<
  "twoColumns",
  Simplify<TextSliceTwoColumnsPrimary>,
  never
>;

/**
 * Slice variation for *Text*
 */
type TextSliceVariation = TextSliceDefault | TextSliceTwoColumns;

/**
 * Text Shared Slice
 *
 * - **API ID**: `text`
 * - **Description**: Text
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextSlice = prismic.SharedSlice<"text", TextSliceVariation>;

/**
 * Primary content in *TextWithImage → Default → Primary*
 */
export interface TextWithImageSliceDefaultPrimary {
  /**
   * Text field in *TextWithImage → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_with_image.default.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * Image field in *TextWithImage → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: text_with_image.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for TextWithImage Slice
 *
 * - **API ID**: `default`
 * - **Description**: TextWithImage
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextWithImageSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TextWithImageSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *TextWithImage → With Button → Primary*
 */
export interface TextWithImageSliceWithButtonPrimary {
  /**
   * Text field in *TextWithImage → With Button → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_with_image.withButton.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * Button Link field in *TextWithImage → With Button → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: text_with_image.withButton.primary.buttonLink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  buttonLink: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Button Text field in *TextWithImage → With Button → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_with_image.withButton.primary.buttonText
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  buttonText: prismic.KeyTextField;

  /**
   * Image field in *TextWithImage → With Button → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: text_with_image.withButton.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * With Button variation for TextWithImage Slice
 *
 * - **API ID**: `withButton`
 * - **Description**: TextWithImage
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextWithImageSliceWithButton = prismic.SharedSliceVariation<
  "withButton",
  Simplify<TextWithImageSliceWithButtonPrimary>,
  never
>;

/**
 * Slice variation for *TextWithImage*
 */
type TextWithImageSliceVariation =
  | TextWithImageSliceDefault
  | TextWithImageSliceWithButton;

/**
 * TextWithImage Shared Slice
 *
 * - **API ID**: `text_with_image`
 * - **Description**: TextWithImage
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextWithImageSlice = prismic.SharedSlice<
  "text_with_image",
  TextWithImageSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      CategoryDocument,
      CategoryDocumentData,
      EventDocument,
      EventDocumentData,
      EventDocumentDataSponsorsItem,
      FooterDocument,
      FooterDocumentData,
      FooterDocumentDataAboutUsLinksItem,
      FooterDocumentDataGetInTouchLinksItem,
      FooterDocumentDataSocialLinksItem,
      NavigationDocument,
      NavigationDocumentData,
      NavigationDocumentDataLinksItem,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      SettingsDocument,
      SettingsDocumentData,
      SponsorDocument,
      SponsorDocumentData,
      AllDocumentTypes,
      AboutSectionSlice,
      AboutSectionSliceDefaultPrimaryFeaturesItem,
      AboutSectionSliceDefaultPrimary,
      AboutSectionSliceVariation,
      AboutSectionSliceDefault,
      EventListingSlice,
      EventListingSliceDefaultPrimary,
      EventListingSliceVariation,
      EventListingSliceDefault,
      GsapSliderSlice,
      GsapSliderSliceDefaultItem,
      GsapSliderSliceVariation,
      GsapSliderSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      ImageSlice,
      ImageSliceDefaultPrimary,
      ImageSliceBannerPrimary,
      ImageSliceVariation,
      ImageSliceDefault,
      ImageSliceBanner,
      ImageCardsSlice,
      ImageCardsSliceDefaultPrimaryCardsItem,
      ImageCardsSliceDefaultPrimary,
      ImageCardsSliceVariation,
      ImageCardsSliceDefault,
      QuoteSlice,
      QuoteSliceDefaultPrimary,
      QuoteSliceVariation,
      QuoteSliceDefault,
      ServicesGridSlice,
      ServicesGridSliceDefaultPrimary,
      ServicesGridSliceDefaultItem,
      ServicesGridSliceVariation,
      ServicesGridSliceDefault,
      SponsorSliderSlice,
      SponsorSliderSliceDefaultPrimary,
      SponsorSliderSliceDefaultItem,
      SponsorSliderSliceVariation,
      SponsorSliderSliceDefault,
      StudioAccordionSlice,
      StudioAccordionSliceDefaultPrimary,
      StudioAccordionSliceDefaultItem,
      StudioAccordionSliceVariation,
      StudioAccordionSliceDefault,
      TextSlice,
      TextSliceDefaultPrimary,
      TextSliceTwoColumnsPrimary,
      TextSliceVariation,
      TextSliceDefault,
      TextSliceTwoColumns,
      TextWithImageSlice,
      TextWithImageSliceDefaultPrimary,
      TextWithImageSliceWithButtonPrimary,
      TextWithImageSliceVariation,
      TextWithImageSliceDefault,
      TextWithImageSliceWithButton,
    };
  }
}
